// ON THE GO MOVING — Blog Index Posts (auto-generated)
// Generated: 2026-04-07
// ==========================================================================

import { BRAND_IMAGES } from "@/lib/brandImages";

export interface BlogIndexPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  excerpt: string;
  image: string;
  readTime: string;
}

export const BLOG_POSTS: BlogIndexPost[] = [
  {
    slug: "redmond-move-day-planning-checklist",
    title: `Redmond Moving Checklist: Parking, Loading Access, and Move-Day Planning`,
    excerpt: `A smooth Redmond move day starts before the truck arrives. The most useful preparation is not a last-minute rush. It is a clear plan for parking, entry, loading, packed boxes, and the person who can answer questions...`,
    image: BRAND_IMAGES.crewEntryway4,
    date: "August 20, 2026",
    category: "Moving Tips & Guides",
    readTime: "11 min read",
  },
  {
    slug: "bellevue-moving-estimate-checklist",
    title: `Bellevue Moving Estimate Checklist: How to Get a More Accurate Quote`,
    excerpt: `A useful moving estimate is not just a number. It is a plan based on what you are moving, where the crew needs to work, and what help you need along the way. For a local Bellevue move, the clearest quote usually...`,
    image: BRAND_IMAGES.crewCarryingOut,
    date: "August 18, 2026",
    category: "Moving Tips & Guides",
    readTime: "12 min read",
  },
  {
    slug: "moving-insurance-what-it-covers-and-what-it-doesnt",
    title: `Moving Insurance: What It Covers and What It Doesn't`,
    date: "August 5, 2026",
    category: "Moving Tips & Guides",
    excerpt: `Most people assume their belongings are fully protected during a move. Most people are wrong. Here is what moving insurance actually covers, what it doesn't, and how to make sure you're not left with a claim that pays pennies on the dollar.`,
    image: BRAND_IMAGES.crewWrappingFurniture,
    readTime: "10 min read",
  },
  {
    slug: "how-to-choose-a-moving-company-10-questions-to-ask",
    title: "How to Choose a Moving Company: 10 Questions to Ask",
    excerpt: "Not sure how to choose a moving company you can actually trust? These 10 questions help Eastside homeowners find a licensed, reliable mover and avoid costly surprises on move day.",
    date: "August 4, 2026",
    category: "Moving Tips & Guides",
    readTime: "10 min read",
    image: BRAND_IMAGES.crewCarryingFurniture,
  },
  {
    slug: "how-to-help-clients-prepare-for-moving-day-after-closing",
    title: "How to Help Clients Prepare for Moving Day After Closing",
    excerpt: "A practical guide for real estate agents on the Eastside. Learn what to tell your clients about preparing for move day after closing, from key handoff logistics to move-in day coordination tips.",
    date: "August 3, 2026",
    category: "Real Estate Agent Resources",
    readTime: "9 min read",
    image: BRAND_IMAGES.crewDoorway2,
  },
  {
    slug: "what-your-clients-need-to-know-about-hiring-movers",
    title: "What Your Clients Need to Know About Hiring Movers",
    excerpt: "A practical guide for real estate agents on the Eastside. Share this with your clients to help them hire the right moving company, avoid common scams, and arrive at closing day ready to move.",
    date: "August 2, 2026",
    category: "Real Estate Agent Resources",
    readTime: "10 min read",
    image: BRAND_IMAGES.crewEntryway1,
  },
  {
    slug: "it-equipment-moving-how-to-relocate-servers-workstations-safely",
    title: "IT Equipment Moving: How to Relocate Servers and Workstations Safely",
    excerpt: "Moving servers, workstations, and IT infrastructure requires more planning than moving furniture. Learn how to relocate your office technology safely with zero data loss and minimal downtime.",
    date: "August 1, 2026",
    category: "Corporate and Office Moving",
    readTime: "11 min read",
    image: BRAND_IMAGES.warehouseInterior,
  },
  {
    slug: "commercial-moving-timeline-what-to-expect",
    title: "Commercial Moving Timeline: What to Expect",
    excerpt: "A week-by-week commercial moving timeline for Eastside businesses. Learn what happens at every stage of an office relocation, from signing the contract to your first day in the new space.",
    date: "July 31, 2026",
    category: "Corporate and Office Moving",
    readTime: "10 min read",
    image: BRAND_IMAGES.customerHandshake,
  },
  {
    slug: "how-to-sell-belongings-before-moving",
    title: "How to Sell a Lifetime of Belongings Before Moving",
    excerpt: "Downsizing and need to sell furniture, collectibles, and household items? Learn which selling method works best for each item type — estate sales, online marketplaces, consignment, and more.",
    date: "July 29, 2026",
    category: "Downsizing & Senior Moving",
    readTime: "12 min read",
    image: BRAND_IMAGES.crewCarryingFurniture,
  },
  {
    slug: "storage-solutions-when-downsizing",
    title: "Storage Solutions When Downsizing: What to Keep, What to Store, and When to Let Go",
    category: "Downsizing & Senior Moving",
    date: "July 28, 2026",
    readTime: "11 min read",
    image: BRAND_IMAGES.warehouseInterior,
    author: "Jason Sexton",
    excerpt: "Using storage when downsizing? Learn how to decide what to store, how long to keep it, and when to let go — so storage becomes a bridge, not a permanent solution."
  },
  {
    slug: "senior-moving-guide-how-to-plan-a-stress-free-move",
    title: "Senior Moving Guide: How to Plan a Stress-Free Move",
    date: "July 27, 2026",
    category: "Downsizing & Senior Moving",
    excerpt: "Planning a move as a senior? This guide covers everything from choosing the right timeline to working with a moving company that understands your needs — so your move goes smoothly from start to finish.",
    image: BRAND_IMAGES.crewMattress,
    readTime: "12 min read"
  },
  {
    slug: "how-to-decide-what-to-keep-when-downsizing",
    title: "How to Decide What to Keep When Downsizing",
    date: "July 26, 2026",
    category: "Downsizing & Senior Moving",
    excerpt: "Struggling to decide what to keep when downsizing? A practical four-category framework for furniture, sentimental items, and everyday belongings — so you can downsize with confidence and without regret.",
    image: BRAND_IMAGES.crewRollingRug,
    readTime: "11 min read"
  },
  {
    slug: "moving-to-a-smaller-home-what-to-expect",
    title: "Moving to a Smaller Home: What to Expect",
    date: "July 25, 2026",
    category: "Downsizing & Senior Moving",
    excerpt: "What to realistically expect when moving to a smaller home — space adjustment, furniture decisions, storage challenges, the emotional side, and how to make the new space feel like home on the Eastside.",
    image: BRAND_IMAGES.crewCarryingOut,
    readTime: "10 min read"
  },
  {
    slug: "downsizing-your-home-step-by-step-guide",
    title: "Downsizing Your Home: A Step-by-Step Guide",
    date: "July 24, 2026",
    category: "Downsizing & Senior Moving",
    excerpt: "A complete step-by-step guide to downsizing your home. How to decide what to keep, handle sentimental items, sell or donate furniture, and plan the logistics of moving to a smaller space on the Eastside.",
    image: BRAND_IMAGES.packingBoxes,
    readTime: "10 min read"
  },
  {
    slug: "what-to-know-before-signing-lease-washington-state",
    title: "What to Know Before Signing a Lease in Washington State (2026)",
    date: "July 24, 2026",
    category: "Renting & Apartments",
    excerpt: "A complete guide to signing a lease in Washington State. Covers tenant rights, notice requirements, security deposit rules, lease terms to watch for, and how to protect yourself before and after signing.",
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "10 min read"
  },
  {
    slug: "apartment-hunting-checklist-what-to-look-for-before-you-sign",
    title: "Apartment Hunting Checklist: What to Look for Before You Sign",
    date: "July 23, 2026",
    category: "Renting & Apartments",
    excerpt: "A complete apartment hunting checklist for renters on the Eastside. What to look for during tours, what to ask before signing, lease red flags to watch for, and how to coordinate your move once you have found the right place.",
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "9 min read"
  },
  {
    slug: "renting-bellevue-vs-seattle-cost-comparison-2026",
    title: "Renting in Bellevue vs. Seattle: A Real Cost Comparison (2026)",
    date: "July 22, 2026",
    category: "Renting & Apartments",
    excerpt: "Bellevue and Seattle are 10 miles apart but involve different tradeoffs for renters. This 2026 guide compares real rent prices by unit type and neighborhood, plus commute costs, parking, and quality of life factors to help you decide where to rent.",
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "9 min read"
  },
  {
    slug: "best-neighborhoods-rent-eastside-seattle-2026",
    title: "Best Neighborhoods to Rent on the Eastside in 2026: A Renter's Guide",
    date: "July 21, 2026",
    category: "Renting & Apartments",
    excerpt: "Not all Eastside neighborhoods are created equal. This 2026 guide breaks down the best places to rent in Bellevue, Kirkland, Redmond, Bothell, and Renton with real price ranges, commute context, and honest assessments of what each area is actually like.",
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "10 min read"
  },
  {
    slug: "how-to-find-apartment-bellevue-kirkland",
    title: "How to Find an Apartment in Bellevue or Kirkland: A Practical Guide",
    date: "July 20, 2026",
    category: "Renting & Apartments",
    excerpt: "The Eastside rental market is competitive and expensive. This guide covers where to search, what to budget, how to put together a strong application, what lease terms to watch for, and how to coordinate your move once you have signed.",
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "9 min read"
  },
  {
    slug: "downsizing-seattle-move-smaller-home",
    title: "Downsizing in Seattle: How to Move to a Smaller Home",
    date: "July 19, 2026",
    category: "Downsizing & Senior Moving",
    excerpt: "A practical guide to downsizing on the Eastside. Learn how to decide what to keep, how to handle furniture that won't fit, when storage makes sense, and how to make the move as smooth as possible.",
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "9 min read"
  },
  {
    slug: "how-to-time-your-move-mortgage-closing-date",
    title: "How to Time Your Move Around Your Mortgage Closing Date",
    date: "July 18, 2026",
    category: "Home Buying",
    excerpt: "Closing dates shift. Movers book out weeks in advance. Here is how to coordinate your move with your mortgage closing, handle date changes, and avoid the most common timing mistakes on the Eastside.",
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "8 min read"
  },
  {
    slug: "best-neighborhoods-buy-home-eastside-seattle",
    title: "Best Neighborhoods to Buy a Home on the Eastside: A City-by-City Guide",
    date: "July 17, 2026",
    category: "Home Buying",
    excerpt: "Bellevue, Kirkland, Redmond, Sammamish, Issaquah, Renton, or Bothell? A practical city-by-city breakdown of the best Eastside neighborhoods to buy a home in 2026, with price ranges, school districts, and commute profiles.",
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "10 min read"
  },
  {
    slug: "first-time-homebuyer-guide-eastside-seattle",
    title: "First-Time Homebuyer Guide for the Eastside: What to Know Before You Buy",
    date: "July 16, 2026",
    category: "Home Buying",
    excerpt: "A step-by-step guide for first-time buyers in Bellevue, Kirkland, Redmond, and Sammamish. Covers pre-approval, affordability, offers, inspections, closing, and moving in.",
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "9 min read"
  },
  {
    slug: "moving-timeline-cheat-sheet-real-estate-agents",
    title: "Moving Timeline Cheat Sheet for Real Estate Agents",
    date: "July 15, 2026",
    category: "Real Estate Agent Resources",
    excerpt: "A stage-by-stage moving timeline for buyer and seller clients, common mistakes to prevent, Eastside cost ranges, and a simple script for introducing On The Go Moving as a trusted referral.",
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "7 min read"
  },
  {
    slug: "how-to-choose-moving-company-for-real-estate-clients",
    title: `How to Choose a Moving Company to Recommend to Your Real Estate Clients`,
    date: `July 14, 2026`,
    category: `Real Estate Agent Resources`,
    excerpt: `A practical guide for Eastside real estate agents. Learn what to look for, what red flags to avoid, and how to build a referral relationship that protects your reputation.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: `8 min read`,
  },
  {
    slug: "what-to-consider-before-signing-office-lease-eastside",
    title: `What to Consider Before Signing a New Office Lease on the Eastside`,
    date: `July 13, 2026`,
    category: `Corporate and Office Moving`,
    excerpt: `Before you sign an Eastside office lease, evaluate location, lease terms, building infrastructure, and moving logistics. A guide for business owners in Bellevue, Redmond, and Kirkland.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: `9 min read`,
  },
  {
    slug: "office-relocation-checklist-lease-to-move-in",
    title: `Office Relocation Checklist: From Lease Signing to Move-In Day`,
    date: "July 12, 2026",
    category: "Corporate and Office Moving",
    excerpt: `Planning an office move on the Eastside? Use this complete phase-by-phase checklist covering every step from lease signing through move-in day — including IT, vendor booking, employee communication, and post-move tasks.`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "10 min read",
  },
  {
    slug: "what-to-do-with-your-stuff-when-selling-a-home",
    title: `What to Do With Your Stuff When Selling a Home: Storage, Staging, and Moving`,
    date: "July 11, 2026",
    category: "Home Selling",
    excerpt: `Selling your home on the Eastside? Learn what to do with your belongings before listing: what to declutter, what to store, and how to coordinate your move so your home shows at its best.`,
    image: BRAND_IMAGES.warehouseInterior,
    readTime: "8 min read",
  },
  {
    slug: "moving-out-after-selling-your-home",
    title: `Moving Out After Selling Your Home: A Complete Checklist`,
    date: "July 7, 2026",
    category: "Home Selling",
    excerpt: `Accepted an offer on your home? Here is the complete moving out checklist for home sellers in Bellevue, Kirkland, Redmond, and the Eastside. Avoid costly mistakes.`,
    image: BRAND_IMAGES.crewFrontDoorExit,
    readTime: "8 min read",
  },
  {
    slug: "renting-vs-buying-eastside-seattle",
    title: `Renting vs. Buying a Home on the Eastside: What Makes Financial Sense Right Now`,
    date: "July 10, 2026",
    category: "Home Buying",
    excerpt: `With median home prices above $1.2 million in Bellevue and Kirkland, the rent-vs-buy decision on the Eastside is not straightforward. Here is a clear financial framework to help you decide.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "9 min read",
  },
  {
    slug: "moving-timeline-for-home-buyers",
    title: `Moving Timeline for Home Buyers: From Offer to Move-In Day`,
    date: "July 7, 2026",
    category: "Home Buying",
    excerpt: `Just had your offer accepted? Here is the exact moving timeline every home buyer needs, from offer acceptance through closing to move-in day on the Eastside.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "7 min read",
  },
  {
    slug: "moving-tips-how-to-pack-up-your-garage-for-moving",
    title: `Moving Tips: How to Pack Up Your Garage for Moving`,
    date: "December 16, 2016",
    category: "Moving Tips & Guides",
    excerpt: `When it comes to moving, packing up the garage can be quite the project. Here are a few helpful moving tips for making the process go swiftly and smoothly.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "how-to-pack-tv-for-moving",
    title: `How To Pack Your Flat Screen TV for Moving | 4 Expert Tips`,
    date: "November 15, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Not sure how to safely pack your TV for moving? Explore four expert tips for quickly and securely transporting your TV to your new home.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "8-tips-move-bad-weather",
    title: `8 Tips to Help You Move in The Rain`,
    date: "October 8, 2018",
    category: "Moving Tips & Guides",
    excerpt: `Moving in bad weather is never easy. These 8 moving tips will help you cope successfully with moving house or apartment in bad weather.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "changing-your-address-essential-checklist",
    title: `An Essential Checklist for Changing Your Address`,
    date: "September 30, 2016",
    category: "Moving Tips & Guides",
    excerpt: `Moving means changing your address. Here's a step by step guide on how to change your address and communicate with people who need your new address.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "4 min read",
  },
  {
    slug: "moving-tips-the-right-way-to-pack-a-bathroom",
    title: `Moving Tips: The Right Way to Pack a Bathroom`,
    date: "October 7, 2016",
    category: "Moving Tips & Guides",
    excerpt: `Getting ready for the big move? Here are some helpful moving tips on how to pack your bathroom efficiently and economically.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },  {
    slug: "how-to-pack-a-storage-unit",
    title: `How to Pack and Organize a Storage Unit | Best Tips for Ease of Access`,
    date: "March 27, 2020",
    category: "Moving Tips & Guides",
    excerpt: `If this is your first time packing a storage unit, our moving experts here at On The Go Moving have compiled a list of 6 helpful, organizational tips for you.`,
    image: BRAND_IMAGES.warehouseInterior,
    readTime: "5 min read",
  },
  {
    slug: "storage-unit-prices",
    title: `Storage Unit Prices`,
    date: "July 16, 2021",
    category: "Moving Tips & Guides",
    excerpt: `Learn more about storage unit prices and what solutions are available to you. Get in touch with On The Go Moving today, for more details.`,
    image: BRAND_IMAGES.teamMemberWarehouse,
    readTime: "4 min read",
  },
  {
    slug: "leave-behind-moving-5-ways-declutter-house",
    title: `What to Leave Behind When Moving: 5 Ways to Declutter Your House`,
    date: "June 26, 2017",
    category: "Moving Tips & Guides",
    excerpt: `Take the process of moving as an opportunity to rid yourself of the clutter that has collected over the years and start fresh. Whether it’s your first big move `,
    image: BRAND_IMAGES.crewFloorProtection1,
    readTime: "3 min read",
  },  {
    slug: "how-to-pack-a-car-for-moving",
    title: `Helpful Tips On How to Pack A Car for Moving`,
    date: "January 16, 2018",
    category: "Moving Tips & Guides",
    excerpt: `Explore helpful tips on how to pack a car for moving, including tricks and strategies for how you can safely and effectively pack your car for your move.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "4 min read",
  },
  {
    slug: "benefits-of-climate-controlled-storage",
    title: `8 Reasons Climate Controlled Storage Units Are Best For Indoor Storage`,
    date: "March 30, 2017",
    category: "Moving Tips & Guides",
    excerpt: `Climate-controlled storage provides many improvements over outdoor storage, and some items even require climate-controlled vaults over outdoor units. Below we’l`,
    image: BRAND_IMAGES.warehouseCratesAlt,
    readTime: "5 min read",
  },
  {
    slug: "tricks-to-unpack-your-home-in-2-days",
    title: `How To Unpack After Moving In 2 Days`,
    date: "October 21, 2016",
    category: "Moving Tips & Guides",
    excerpt: `How to unpack after a move can be crucial, if you don’t do it the right way it can turn in a daunting experience. Follow our tips to unpack quickly & smoothly!`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "3 min read",
  },
  {
    slug: "moving-into-new-house",
    title: `11 Tips To Do First After Moving Into A New House`,
    date: "November 30, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Congratuations on your new home! Now what? Explore the first 11 things to do after moving into your new house so you can feel comfortable in your new home as so`,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "5 min read",
  },
  {
    slug: "hiring-professional-movers-vs-moving-yourself",
    title: `What To Know About Hiring Professional Movers vs Moving Yourself`,
    date: "December 1, 2021",
    category: "Moving Tips & Guides",
    excerpt: `Have trouble between hiring a moving company or DIY for moving? Read now for more information about the pros and cons of hiring and DIY moving.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "housewarming-party-ideas-and-food",
    title: `Ideas For The Ultimate Housewarming Party | Planning Food, Themes, Games, & Drinks`,
    date: "September 27, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Planning a housewarming party doesn’t need to be stress-inducing at all. Rather it gives you a fun chance to whip out your creative skills and introduce people.`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "5 min read",
  },
  {
    slug: "first-time-moving-heres-simple-checklist",
    title: `Checklist: First Time Moving Out | Tips For Packing Room By Room`,
    date: "August 22, 2017",
    category: "Moving Tips & Guides",
    excerpt: `Now that you’re ready to move out for the first time, the next step is to get organized and plan your move down to the smallest detail. To make things easier fo`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-dishes",
    title: `How To Pack Dishes | Kitchenware, Pots and Pans, and Glasses`,
    date: "September 27, 2019",
    category: "Moving Tips & Guides",
    excerpt: `The last thing you want is breaking any of your dishes while moving, that's why we've compiled a 5 step process to packing your dishes safely and securely.`,
    image: BRAND_IMAGES.crewWrappingFurniture,
    readTime: "3 min read",
  },  {
    slug: "what-not-to-pack-when-moving-non-allowable-items-explained",
    title: `What Not to Pack When Moving: Non-Allowable Items Explained`,
    date: "August 7, 2018",
    category: "Moving Tips & Guides",
    excerpt: `A professional moving company will transport anything that you ask them to, right? Actually, most moving companies have certain items that they cannot transport`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "3 min read",
  },
  {
    slug: "how-much-do-you-tip-movers",
    title: `How Much To Tip Movers?`,
    date: "March 18, 2021",
    category: "Moving Tips & Guides",
    excerpt: `Do You Need to Tip Movers? Here are five things to consider when deciding how much to tip movers. Read more on this article!`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "7 min read",
  },
  {
    slug: "simplify-move-turn-move-road-trip",
    title: `How to Simplify Your Move: Turn Your Move Into a Road Trip`,
    date: "June 5, 2017",
    category: "Moving Tips & Guides",
    excerpt: `Moving from one place to another presents unique challenges to your family, especially when the move is a far one. However, there are several things you can do `,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "4 min read",
  },
  {
    slug: "organizing-small-spaces",
    title: `14 Organizing Tips For Maximizing A Small Space`,
    date: "September 27, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Minimalizing and moving to smaller homes is a growing movement in the 21st Century. How do you organize and maximize the space in your house?`,
    image: BRAND_IMAGES.crewCarryingOut,
    readTime: "6 min read",
  },
  {
    slug: "how-to-choose-the-best-neighborhood-when-moving-to-a-new-city",
    title: `How to Choose the Best Neighborhood When Moving to a New City`,
    date: "April 4, 2019",
    category: "Local Guides",
    excerpt: `What should you take into consideration when making the decision to move? Read the most important factors to consider when choosing to live in a city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-101-how-to-pack-your-electronics-for-moving",
    title: `Moving 101: How to Pack Your Electronics for Moving`,
    date: "January 17, 2017",
    category: "Moving Tips & Guides",
    excerpt: `If you're wondering how to pack your electronics for moving, here's how to safely transport your desk to the new home.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "5-questions-before-hiring-commercial-moving-company",
    title: `5 Questions to Ask Before Hiring a Moving Company (Seattle Checklist)`,
    date: "September 23, 2015",
    category: "Corporate & Office Moving",
    excerpt: `Not all moving companies are created equal. Before you sign anything, ask these 5 questions to protect your belongings and avoid hidden fees.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "3 min read",
  },
  {
    slug: "moving-hacks",
    title: `25 Clever Moving Hacks and Advice to Make Your Move Less Stressful`,
    date: "August 8, 2023",
    category: "Moving Tips & Guides",
    excerpt: `With the moving hacks here go for a better and faster move. Read to find some great moving tips to avoid stress and save money. Contact us today!`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "10-expert-tips-to-make-your-winter-move-an-easier-mission",
    title: `10 Expert Tips For Easier Moving In The Winter`,
    date: "December 20, 2018",
    category: "Moving Tips & Guides",
    excerpt: `Moving in the winter can actually be great timing, check out our tips to make your life easier. Make your plans and prepping ahead and let us help you handle th`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "11-tips-for-an-easy-diy-move",
    title: `11 Tips For An Easy DIY Move You Should Know`,
    date: "December 1, 2021",
    category: "Moving Tips & Guides",
    excerpt: `There are a lot of ways to simplify your DIY move. Here are our top 11 tips for a smooth and easy DIY move. Check out and read now for more information.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "4 min read",
  },
  {
    slug: "10-things-you-need-when-moving-into-your-new-home",
    title: `10 Things You Need When Moving Into Your New Home`,
    date: "March 19, 2018",
    category: "Moving Tips & Guides",
    excerpt: `Are you getting ready to move into a new house, but are not sure if you have everything you need? We've collected an important list of 10 things you may need to`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "4 min read",
  },
  {
    slug: "advantages-of-warehousing",
    title: `Benefits & Advantages of Warehousing`,
    date: "March 26, 2023",
    category: "Corporate & Office Moving",
    excerpt: `The advantages of warehousing benefit businesses from reduced delivery time to storing benefits. Learn how warehousing helps proprietors & consumers!`,
    image: BRAND_IMAGES.brandedTruck,
    readTime: "4 min read",
  },
  {
    slug: "15-signs-of-a-worst-moving-company",
    title: `15 Signs of a Worst Moving Company`,
    date: "May 30, 2022",
    category: "Moving Tips & Guides",
    excerpt: `Read On The Moving’s blog article about the list of signs of the worst moving companies you should remember before moving.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "3 min read",
  },
  {
    slug: "what-to-pack-first-moving",
    title: `Tips For What To Pack First When You're Moving`,
    date: "January 11, 2020",
    category: "Moving Tips & Guides",
    excerpt: `Deciding to what to pack first can feel like a daunting task. To help your move go smoothly and stress-free, we've complied a step by step list.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "how-to-meet-your-neighbors",
    title: `How To Meet Your New Neighbors | 7 Non-Awkward Tips For Introducing Yourself`,
    date: "September 27, 2019",
    category: "Moving Tips & Guides",
    excerpt: `A professional moving company will take care of all the packing, loading, and actual moving freeing you up to meet the neighbors!`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "4 min read",
  },
  {
    slug: "how-many-trips-does-a-local-move-really-take",
    title: `How Many Trips Does a Local Move Really Take?`,
    date: "December 21, 2024",
    category: "Moving Tips & Guides",
    excerpt: `Planning a move? Discover how many trips for a local move it takes and learn tips to minimize moving truck trips for local moves efficiently`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "3 min read",
  },  {
    slug: "best-things-to-do-in-everett-wa",
    title: `10 Exciting Things To Do In Everett In 2021`,
    date: "January 1, 2021",
    category: "Local Guides",
    excerpt: `Discover the best things to do in Everett, WA, including waterfront attractions, parks, museums, dining, and family-friendly activities.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-announce-your-office-relocation-5-great-tips",
    title: `How to Announce Your Office Relocation 5 Great Tips`,
    date: "November 29, 2021",
    category: "Corporate & Office Moving",
    excerpt: `Here are the great top five tips on how you can announce your office relocation to your employees. Be positive and upbeat. Check out now for more info.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "3 min read",
  },
  {
    slug: "best-time-to-rent-an-apartment-guide",
    title: `Best Time to Rent an Apartment An Essential Guide`,
    date: "September 1, 2022",
    category: "Renting & Apartments",
    excerpt: `Need to know which is the best time to rent an apartment? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },  {
    slug: "essential-tools-needed-for-a-smooth-move",
    title: `Essential Tools Needed for a Smooth Move`,
    date: "August 22, 2024",
    category: "Moving Tips & Guides",
    excerpt: `Discover essential packing supplies and tools like the heavy duty dolly needed for a smooth move. Ensure your belongings are secure and easy to transport.`,
    image: BRAND_IMAGES.crewStaircaseExit,
    readTime: "3 min read",
  },
  {
    slug: "eco-friendly-moving-sustainable-practices-for-your-next-move",
    title: `Eco-Friendly Moving: Sustainable Practices for Your Next Move`,
    date: "December 21, 2024",
    category: "Moving Tips & Guides",
    excerpt: `Make your move sustainable with eco-friendly moving tips. Use environmentally friendly moving boxes and hire green movers for a low-waste relocation.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "3 min read",
  },
  {
    slug: "moving-elderly-parents-out-of-their-home",
    title: `How To Relocate Your Elderly Parents Smoothly For Them`,
    date: "May 15, 2019",
    category: "Downsizing & Senior Moving",
    excerpt: `It can be hard when it comes time to move your elderly parents. To help the process go smoothly, we've compiled 7 tips for you and them.`,
    image: BRAND_IMAGES.residentialService,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-shoes-for-moving-8-tips",
    title: `8 Tips On How To Pack Shoes For Moving`,
    date: "September 28, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Remove the stress of packing your shoe collection, here are 8 simple tips to sort through and pack your shoe for moving. Don't forget to leave a pair out for mo`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "4 min read",
  },
  {
    slug: "renting-a-house-for-the-first-time",
    title: `5 Tips For Renting A House For The First Time`,
    date: "July 23, 2019",
    category: "Renting & Apartments",
    excerpt: `Before you sign the lease on your first rental, there are a couple of things you should know. Read more information in our blog post.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "5 min read",
  },
  {
    slug: "living-on-mercer-island",
    title: `Living On Mercer Island Washington`,
    date: "January 22, 2021",
    category: "Local Guides",
    excerpt: `Want to know what living on Mercer Island is like? Lucky for you, residents that live in Mercer Island Washington have great things to say about their community`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },  {
    slug: "things-to-do-in-lynnwood-wa",
    title: `Things to Do in Lynnwood WA`,
    date: "September 2, 2021",
    category: "Local Guides",
    excerpt: `No matter whether you're planning a visit or to stay, you can count on a variety of fun things to do in Lynnwood, Washington. Read more!`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "living-in-renton-wa",
    title: `15 Things to Know About Living in Renton`,
    date: "August 4, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Renton, Washington? Here are 15 things you will need to know before you make the big move to the southeast shore of Lake Washington`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-edmonds-wa",
    title: `Things to Do in Edmonds WA`,
    date: "September 2, 2021",
    category: "Local Guides",
    excerpt: `From outdoor activities to community-wide events, you can find many fun things to do in Edmonds, WA. They have the best restaurants too! Read more!`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-on-mercer-island",
    title: `Things to do on Mercer Island`,
    date: "June 2, 2021",
    category: "Local Guides",
    excerpt: `Don’t forget to share all of your local tips in the comments below and tell us what your favorite thing to do on Mercer Island is!Need help planning a move to M`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-sammamish",
    title: `Things To Do In Sammamish`,
    date: "February 7, 2021",
    category: "Local Guides",
    excerpt: `Sammamish is full of all kind of events and activities to explore. Learn more about the area and the things to do in Sammamish!`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-kirkland-wa",
    title: `Things to Do in Kirkland, WA`,
    date: "October 1, 2020",
    category: "Local Guides",
    excerpt: `Looking for things to do in Kirkland, WA? Explore waterfront parks, dining, shopping, outdoor activities, and local attractions for all ages.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },  {
    slug: "fun-things-to-do-in-bothell-wa",
    title: `10 Fun Things To Do In Bothell WA in 2021 | Plus Free Things To Do With Kids`,
    date: "January 6, 2021",
    category: "Local Guides",
    excerpt: `Explore the best things to do in Bothell, WA, from outdoor parks and family activities to local dining and entertainment. Discover top attractions and insider `,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-bellevue",
    title: `15 Best Things To Do In Bellevue For Fun`,
    date: "July 20, 2020",
    category: "Local Guides",
    excerpt: `Bellevue is known for its beautiful sites and downtown skyline of gleaming high-rises. Find things to do in Bellevue WA at night or fun activities with kids. Do`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-prepare-for-movers",
    title: `How to Prepare for Movers to Arrive?`,
    date: "August 23, 2023",
    category: "Moving Tips & Guides",
    excerpt: `After hiring a moving company for your upcoming move, you must know how to prepare for movers. To prepare for your movers before they arrive on a moving day.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "how-to-protect-fragile-items-during-a-move",
    title: `How to Protect Fragile Items During a Move`,
    date: "December 20, 2024",
    category: "Moving Tips & Guides",
    excerpt: `Learn how to pack fragile items for moving safely. Get expert advice on protecting glass during a move and preventing damage with smart packing techniques.`,
    image: BRAND_IMAGES.crewEntryway2,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-issaquah",
    title: `15 Top Things To Do In Issaquah`,
    date: "June 8, 2020",
    category: "Local Guides",
    excerpt: `The Pacific Northwest is a beautiful and interesting place to live, and Issaquah is no exception. Here are 15 places to check out after your Issaquah move.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "how-to-move-large-furniture-safely-and-efficiently",
    title: `How to Move Large Furniture Safely and Efficiently`,
    date: "December 20, 2024",
    category: "Moving Tips & Guides",
    excerpt: `Learn furniture moving techniques to handle bulky items safely. Discover safe ways to move heavy furniture and tips for moving it upstairs efficiently`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "best-restaurants-in-seattle",
    title: `Best Seattle Seafood & International Restaurants to Visit in 2022`,
    date: "November 18, 2015",
    category: "Local Guides",
    excerpt: `On The Go Moving shares the names of several wonderful Seattle restaurants so that newcomers can enjoy the beauty and diversity of the city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "attractions-in-seattle",
    title: `Seattle Attractions - Places To Visit in the Emerald City`,
    date: "July 4, 2023",
    category: "Local Guides",
    excerpt: `Find Seattle attractions to know the best places and the best things to do in Seattle. Know more about the top-rated & must-see attractions. Visit us today!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "shopping-in-seattle",
    title: `Seattle Shopping: The Best Places for New Residents to Visit`,
    date: "March 26, 2023",
    category: "Local Guides",
    excerpt: `Find the best options while shopping in Seattle. We can show you the best options in the downtown shopping district!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-seattle-in-summer",
    title: `15 Fun Things To Do In Seattle In Summer`,
    date: "July 7, 2020",
    category: "Local Guides",
    excerpt: `Summers in Seattle, the seaport city of the West Coast, are unmatched. Here are 15 fun things to do in the city this summer to truly experience Seattle.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "seattle-packing-tips-plastic-bins-or-cardboard-boxes",
    title: `Seattle Packing Tips: Plastic Bins or Cardboard Boxes?`,
    date: "September 2, 2016",
    category: "Moving Tips & Guides",
    excerpt: `Are you packing for a move? Here are the pros and cons between cardboard boxes and plastic bins. Read on for helpful Seattle packing tips:`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "parks-near-downtown-seattle",
    title: `Parks Near Downtown Seattle, WA`,
    date: "June 3, 2022",
    category: "Local Guides",
    excerpt: `Welcome to the official On The Go Moving site. Go through the blog post to see the best Parks Near Downtown Seattle, WA that makes Seattle such an exciting urba`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-to-seattle",
    title: `Moving to Seattle in 2026: What Living Here Is Actually Like (Honest Guide)`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Seattle actually like? Real talk on the Seattle Freeze, neighborhoods, cost of living, the rain, and what locals wish they'd known before moving.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "restaurant-in-redmond",
    title: `Best Restaurants in Redmond WA`,
    date: "January 7, 2022",
    category: "Local Guides",
    excerpt: `Looking for the best restaurant around Redmond that offers healthy and delicious foods? This article is what you're looking for! Read more and call us today!`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "best-things-to-do-in-redmond",
    title: `22 Top Things To Do in Redmond`,
    date: "June 4, 2021",
    category: "Local Guides",
    excerpt: `Explore the best things to do in Redmond, WA, parks, trails, tech attractions, family fun, shopping, and local experiences for residents and visitors.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-shoreline-wa",
    title: `Things to Do in Shoreline, WA: Parks, Attractions & Activities`,
    date: "November 21, 2020",
    category: "Local Guides",
    excerpt: `Discover the best things to do in Shoreline, WA, including parks, outdoor activities, dining, and local attractions for all ages.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "parks-in-bellevue",
    title: `Parks In Bellevue WA | Water Recreation, Park Near Bellevue Square`,
    date: "July 11, 2020",
    category: "Local Guides",
    excerpt: `Bellevue is known for having some beautiful parks. Form lushish green to refreshing water, check out the top 7 parks to visit in the Bellevue area!`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "parks-in-lynnwood",
    title: `Best Parks in Lynnwood`,
    date: "November 23, 2021",
    category: "Local Guides",
    excerpt: `Discover the best trails, hiking and other outdoor activities in the best parks in lynnwood. On the Go moving has different locations to explore.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "seattle-restaurant-fremont",
    title: `Best Restaurants in Fremont Seattle, WA`,
    date: "January 11, 2022",
    category: "Local Guides",
    excerpt: `Are you looking for the best restaurants in Fremont, Seattle that will satisfy your cravings? This article is for you. Read more to find out!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "lake-sammamish-parks",
    title: `Lake Sammamish Parks`,
    date: "August 3, 2021",
    category: "Local Guides",
    excerpt: `Are you looking for the ideal park in Lake Sammamish? Visit On The Go Moving, to learn about the best parks & things to do in and around Sammamish, Washington.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "kirkland-waterfront",
    title: `Kirkland Waterfront`,
    date: "August 9, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the Kirkland's iconic waterfront, find the best parks, trails, and waterfront restaurants in the area. Visit On The Go Moving for more details.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "parks-in-redmond-wa",
    title: `Redmond Parks`,
    date: "June 7, 2021",
    category: "Local Guides",
    excerpt: `Discover the best parks in Redmond WA, from trails to family-friendly spaces, plus local tips for living and moving in Redmond.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "what-is-seattle-known-for-food-sights",
    title: `What Seattle Is Known For, Best Food & Iconic Sights`,
    date: "April 29, 2021",
    category: "Local Guides",
    excerpt: `Explore what Seattle is known for, iconic food and best sights from Pike Place Market to Space Needle, plus local travel tips and moving insights.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "mercer-island-restaurants",
    title: `The Best Restaurants, Parks, & Recreation Centers in Mercer Island`,
    date: "November 23, 2021",
    category: "Local Guides",
    excerpt: `Looking for best restaurants, parks and recreation center in Mercer Island?On the Go moving has different locations to explore. Learn more.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "how-to-move-a-piano",
    title: `Do It Yourself: Best Way To Move A Piano`,
    date: "November 20, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Moving your piano can be daunting task. Here are our expert tips to make sure your piano and your back both remain intact throughout the process.`,
    image: BRAND_IMAGES.crewRamp,
    readTime: "4 min read",
  },  {
    slug: "office-moving-tips",
    title: `How To Keep Your Office Moving Organized And Easy`,
    date: "August 1, 2017",
    category: "Corporate & Office Moving",
    excerpt: `Moving an entire office can at first seem overwhelming. To combat potential chaos, we've created a month by month office moving plan to keep you organized.`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "4 min read",
  },
  {
    slug: "best-office-organization-systems",
    title: `Office Organization Systems | How To Organize An Office Space | Tips For Arranging Your Work`,
    date: "March 23, 2020",
    category: "Corporate & Office Moving",
    excerpt: `Struggling to keep your office organized? Follow our eight easy steps to arrange your space into a system that works for you and your team.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },  {
    slug: "residential-moving-services-guide",
    title: `What's Included in a Residential Move? A Plain-English Guide for Seattle Homeowners`,
    date: "November 28, 2023",
    category: "Moving Tips & Guides",
    excerpt: `Confused about what residential movers actually do? This guide breaks down every service, loading, packing, storage, and more, so you know exactly what to expect.`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "4 min read",
  },
  {
    slug: "how-to-pack-clothes-for-moving",
    title: `How to Pack Clothes For Moving | Best Way To Move Clothes`,
    date: "November 29, 2019",
    category: "Moving Tips & Guides",
    excerpt: `Packing clothes for moving can seem like a daunting task, make it easy for yourself by exploring our best tips for how to pack your clothes efficiently and simp`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "6 min read",
  },
  {
    slug: "moving-to-a-new-city-alone",
    title: `Moving To A New City Alone | What To Do & How To Face The Challenges Of Moving Out Of State`,
    date: "January 13, 2020",
    category: "Renting & Apartments",
    excerpt: `Moving to a new city alone can feel frightening and lonely. Sometimes you feel you just don't know what to do next or how to fit in. To help make this next exci`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-seattle-in-winter",
    title: `Things To Do in Seattle in Winter`,
    date: "January 5, 2021",
    category: "Local Guides",
    excerpt: `If you're looking for things to do in Seattle during winter, then time to discover all Seattle has to offer. Seattle has no shortage of fun things to do during `,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "apartment-moving-tips",
    title: `Apartment Moving Tips: What Renters Need to Know Before Move Day`,
    date: "May 21, 2020",
    category: "Renting & Apartments",
    excerpt: `Elevator reservations, parking permits, narrow hallways, apartment moves have unique challenges. Here's how to prepare so nothing slows you down.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "5 min read",
  },
  {
    slug: "moving-to-bellevue",
    title: `Moving to Bellevue WA in 2026: What Living Here Is Actually Like`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Bellevue, WA actually like? Honest guide on neighborhoods, cost of living, schools, the light rail, and what Reddit locals say about moving to Bellevue.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "7 min read",
  },
  {
    slug: "moving-to-kirkland",
    title: `Moving to Kirkland WA in 2026: What Living Here Is Actually Like`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Kirkland, WA actually like? Honest guide on the waterfront, neighborhoods, Google's campus, Cross Kirkland Corridor, and what Reddit locals say.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "7 min read",
  },
  {
    slug: "moving-to-redmond",
    title: `Moving to Redmond WA in 2026: What Living Here Is Actually Like`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Redmond, WA actually like? Honest guide on Microsoft campus life, bikeability, Derby Days, neighborhoods, and what Reddit locals say about moving to Redmond.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "7 min read",
  },
  {
    slug: "moving-to-sammamish",
    title: `Moving to Sammamish WA in 2026: What Living Here Is Actually Like`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Sammamish, WA actually like? Honest guide on the plateau bubble, school districts, neighborhoods, power outages, and what Reddit locals say.`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "8 min read",
  },
  {
    slug: "moving-to-bothell",
    title: `Moving to Bothell WA in 2026: What Living Here Is Actually Like`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Bothell, WA actually like? Honest guide on McMenamins Anderson School, Woodinville wine country, the Sammamish River Trail, and what Reddit locals say.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "7 min read",
  },
  {
    slug: "moving-to-issaquah",
    title: `Moving to Issaquah WA in 2026: What Living Here Is Actually Like`,
    date: "May 14, 2026",
    category: "Local Guides",
    excerpt: `What is living in Issaquah, WA actually like? Honest guide on the salmon hatchery, Cougar Mountain, Snoqualmie Pass access, neighborhoods, and what Reddit locals say.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "7 min read",
  }
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export const BLOG_CATEGORIES = ["All", "Home Buying", "Home Selling", "Renting & Apartments", "Downsizing & Senior Moving", "Corporate & Office Moving", "Real Estate Agent Resources", "Moving Tips & Guides", "Local Guides"];
